import type {
  BossRaidDefinition,
  CharacterDefinition,
  NormalRaidBossDefinition,
  SkinDefinition,
  SkillDefinition,
  StageDefinition,
  WorldDefinition,
} from './src/types/gameDesign';
import {
  getBossRaidMaxHp,
  NORMAL_RAID_DIAMOND_REWARDS,
} from './game_balance_runtime';

export const gameCatalogVersion = 1;

const MAX_SKILL_LEVEL = 5;

function skill(definition: Omit<SkillDefinition, 'maxLevel'>): SkillDefinition {
  return {
    maxLevel: MAX_SKILL_LEVEL,
    ...definition,
  };
}

const CHAPTER_BLUEPRINT = [
  {
    chapterIndex: 1,
    codeSuffix: 'entrance',
    nameSuffix: 'Entrance',
    themeSuffix: 'Frontier',
    isBossChapter: false,
  },
  {
    chapterIndex: 2,
    codeSuffix: 'core',
    nameSuffix: 'Heartland',
    themeSuffix: 'Core',
    isBossChapter: false,
  },
  {
    chapterIndex: 3,
    codeSuffix: 'boss',
    nameSuffix: 'Boss Domain',
    themeSuffix: 'Boss',
    isBossChapter: true,
  },
] as const;

const WORLD_BLUEPRINT = [
  {
    id: 1,
    code: 'meadow',
    name: 'Meadow',
    theme: 'Open grassland',
    bossId: 'king_slime',
    bossName: 'King Slime',
    normalMonsters: ['slime', 'sprout_wolf', 'bloom_boar'],
    eliteMonster: 'meadow_guardian',
  },
  {
    id: 2,
    code: 'desert',
    name: 'Desert',
    theme: 'Sandstorm frontier',
    bossId: 'sand_colossus',
    bossName: 'Sand Colossus',
    normalMonsters: ['scarab', 'sand_wolf', 'dune_serpent'],
    eliteMonster: 'mirage_hunter',
  },
  {
    id: 3,
    code: 'snowfield',
    name: 'Snowfield',
    theme: 'Frozen valley',
    bossId: 'frost_yeti',
    bossName: 'Frost Yeti',
    normalMonsters: ['ice_sprite', 'snow_hound', 'frozen_turtle'],
    eliteMonster: 'aurora_stalker',
  },
  {
    id: 4,
    code: 'forest',
    name: 'Forest',
    theme: 'Ancient woods',
    bossId: 'ent_queen',
    bossName: 'Ent Queen',
    normalMonsters: ['moss_imp', 'thorn_fox', 'vine_lurker'],
    eliteMonster: 'canopy_warden',
  },
  {
    id: 5,
    code: 'ruins',
    name: 'Ruins',
    theme: 'Forgotten stone halls',
    bossId: 'lich_lord',
    bossName: 'Lich Lord',
    normalMonsters: ['bone_scout', 'crypt_bat', 'cursed_knight'],
    eliteMonster: 'obelisk_keeper',
  },
  {
    id: 6,
    code: 'coast',
    name: 'Coast',
    theme: 'Storm shoreline',
    bossId: 'kraken',
    bossName: 'Kraken',
    normalMonsters: ['reef_crab', 'tide_serpent', 'shell_guard'],
    eliteMonster: 'storm_navigator',
  },
  {
    id: 7,
    code: 'skyreach',
    name: 'Skyreach',
    theme: 'Floating isles',
    bossId: 'thunder_roc',
    bossName: 'Thunder Roc',
    normalMonsters: ['wind_wisp', 'cloud_ram', 'storm_harpy'],
    eliteMonster: 'tempest_knight',
  },
  {
    id: 8,
    code: 'abyss',
    name: 'Abyss',
    theme: 'Sunless trench',
    bossId: 'shadow_behemoth',
    bossName: 'Shadow Behemoth',
    normalMonsters: ['void_mite', 'abyss_hound', 'shade_siren'],
    eliteMonster: 'nightmare_keeper',
  },
  {
    id: 9,
    code: 'magma_frontier',
    name: 'Magma Frontier',
    theme: 'Volcanic approach',
    bossId: 'magma_titan',
    bossName: 'Magma Titan',
    normalMonsters: ['ember_imp', 'lava_hound', 'basalt_golem'],
    eliteMonster: 'crater_sentinel',
  },
  {
    id: 10,
    code: 'red_dragon_lair',
    name: 'Red Dragon Lair',
    theme: 'Core of the volcano',
    bossId: 'red_dragon',
    bossName: 'Red Dragon',
    normalMonsters: ['ash_wyvern', 'magma_drake', 'obsidian_guard'],
    eliteMonster: 'inferno_herald',
  },
] as const;

function titleize(value: string): string {
  return value
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function getMonsterType(
  chapterIndex: number,
  stageNumberInChapter: number,
): 'normal' | 'elite' | 'boss' {
  if (chapterIndex === 3 && stageNumberInChapter === 10) {
    return 'boss';
  }

  if (stageNumberInChapter === 5 || stageNumberInChapter === 9) {
    return 'elite';
  }

  return 'normal';
}

function getMonsterName(
  worldIndex: number,
  monsterType: 'normal' | 'elite' | 'boss',
  stageNumberInChapter: number,
): {monsterId: string; monsterName: string} {
  const world = WORLD_BLUEPRINT[worldIndex];

  if (monsterType === 'boss') {
    return {
      monsterId: world.bossId,
      monsterName: world.bossName,
    };
  }

  if (monsterType === 'elite') {
    return {
      monsterId: world.eliteMonster,
      monsterName: titleize(world.eliteMonster),
    };
  }

  const normalMonsterId =
    world.normalMonsters[(stageNumberInChapter - 1) % world.normalMonsters.length];

  return {
    monsterId: normalMonsterId,
    monsterName: titleize(normalMonsterId),
  };
}

export const CHARACTER_DEFINITIONS: CharacterDefinition[] = [
  {
    id: 'knight',
    name: 'Knight',
    role: 'Attack and defense',
    baseAttack: 10,
    attackGrowthPerLevel: 2,
    baseHp: 200,
    hpGrowthPerLevel: 20,
  },
  {
    id: 'mage',
    name: 'Mage',
    role: 'Utility and special effects',
    baseAttack: 15,
    attackGrowthPerLevel: 5,
    baseHp: 100,
    hpGrowthPerLevel: 10,
  },
  {
    id: 'archer',
    name: 'Archer',
    role: 'Speed and precision',
    baseAttack: 13,
    attackGrowthPerLevel: 3,
    baseHp: 150,
    hpGrowthPerLevel: 15,
  },
  {
    id: 'rogue',
    name: 'Rogue',
    role: 'Economy and luck',
    baseAttack: 14,
    attackGrowthPerLevel: 4,
    baseHp: 130,
    hpGrowthPerLevel: 13,
  },
  {
    id: 'healer',
    name: 'Healer',
    role: 'Sustain and survival',
    baseAttack: 9,
    attackGrowthPerLevel: 2,
    baseHp: 80,
    hpGrowthPerLevel: 8,
  },
];

export const WORLD_DEFINITIONS: WorldDefinition[] = WORLD_BLUEPRINT.map(world => ({
  id: world.id,
  code: world.code,
  name: world.name,
  theme: world.theme,
  bossId: world.bossId,
  bossName: world.bossName,
  chapters: CHAPTER_BLUEPRINT.map(chapter => ({
    chapterIndex: chapter.chapterIndex,
    code: `${world.code}_${chapter.codeSuffix}`,
    name: `${world.name} ${chapter.nameSuffix}`,
    theme: `${world.theme} ${chapter.themeSuffix}`,
    isBossChapter: chapter.isBossChapter,
  })),
}));

export const STAGE_DEFINITIONS: StageDefinition[] = WORLD_BLUEPRINT.flatMap(
  (world, worldIndex) =>
    CHAPTER_BLUEPRINT.flatMap(chapter =>
      Array.from({length: 10}, (_, index) => {
        const stageNumberInChapter = index + 1;
        const stageNumberInWorld = (chapter.chapterIndex - 1) * 10 + stageNumberInChapter;
        const stageNumberGlobal = (world.id - 1) * 30 + stageNumberInWorld;
        const monsterType = getMonsterType(chapter.chapterIndex, stageNumberInChapter);
        const monster = getMonsterName(worldIndex, monsterType, stageNumberInChapter);
        const baseHp =
          800 +
          world.id * 450 +
          chapter.chapterIndex * 350 +
          stageNumberInChapter * 140;
        const bossHpMultiplier = monsterType === 'boss' ? 7 : monsterType === 'elite' ? 2.5 : 1;

        return {
          id: stageNumberGlobal,
          worldId: world.id,
          worldCode: world.code,
          chapterIndex: chapter.chapterIndex,
          chapterCode: `${world.code}_${chapter.codeSuffix}`,
          stageNumberInChapter,
          stageNumberInWorld,
          stageNumberGlobal,
          name: `${world.name} ${chapter.nameSuffix} ${stageNumberInChapter}`,
          monsterId: monster.monsterId,
          monsterName: monster.monsterName,
          monsterType,
          monsterHp: Math.round(baseHp * bossHpMultiplier),
          monsterAttack: Math.round(
            12 +
              world.id * 5 +
              chapter.chapterIndex * 4 +
              stageNumberInChapter * (monsterType === 'boss' ? 2 : 1),
          ),
          attackIntervalSec: monsterType === 'boss' ? 6 : monsterType === 'elite' ? 8 : 10,
          rewardGold: Math.round(
            120 +
              world.id * 25 +
              chapter.chapterIndex * 20 +
              stageNumberInChapter * 10 +
              (monsterType === 'boss' ? 200 : monsterType === 'elite' ? 80 : 0),
          ),
          rewardCharacterExp: Math.round(
            30 +
              world.id * 5 +
              stageNumberInWorld +
              (monsterType === 'boss' ? 30 : monsterType === 'elite' ? 12 : 0),
          ),
          unlocksBossRaidStage:
            chapter.chapterIndex === 3 && stageNumberInChapter === 10 ? world.id : undefined,
        };
      }),
    ),
);

export const NORMAL_RAID_BOSSES: NormalRaidBossDefinition[] = WORLD_DEFINITIONS.map(
  world => {
    const reward = NORMAL_RAID_DIAMOND_REWARDS.find(entry => entry.stage === world.id);

    if (!reward) {
      throw new Error(`Missing normal raid reward data for stage ${world.id}`);
    }

    return {
      id: `normal_raid_${world.bossId}`,
      stage: world.id,
      name: world.bossName,
      skinId: `skin_${world.bossId}`,
      firstClearDiamondReward: reward.firstClearDiamondReward,
      repeatDiamondReward: reward.repeatDiamondReward,
    };
  },
);

export const BOSS_RAID_DEFINITIONS: BossRaidDefinition[] = WORLD_DEFINITIONS.map(world => ({
  id: `boss_raid_${world.bossId}`,
  stage: world.id,
  worldId: world.id,
  name: world.bossName,
  maxHp: getBossRaidMaxHp(world.id),
  unlockWorldId: world.id,
  raidWindowHours: 4,
  joinWindowMinutes: 10,
  maxParticipants: 30,
}));

export const SKIN_DEFINITIONS: SkinDefinition[] = WORLD_DEFINITIONS.map(world => ({
  id: `skin_${world.bossId}`,
  sourceBossId: `normal_raid_${world.bossId}`,
  attackBonusRate: world.id * 0.02,
  summonId: `summon_${world.bossId}`,
  uniqueEffectId: `${world.bossId}_unique_effect`,
}));

const knightSkills: SkillDefinition[] = [
  skill({
    id: 'knight_iron_wall',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 1,
    treeNodeIndex: 1,
    name: 'Iron Wall',
    shortDescription: 'Reduce incoming damage.',
    effectType: 'incoming_damage_reduction_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.05, unit: 'percent'},
  }),
  skill({
    id: 'knight_steel_will',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 2,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'knight_iron_wall',
    name: 'Steel Will',
    shortDescription: 'Boost combo damage.',
    effectType: 'combo_attack_bonus_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.05, unit: 'percent'},
  }),
  skill({
    id: 'knight_shield_charge',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 3,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'knight_steel_will',
    name: 'Shield Charge',
    shortDescription: 'Charge raid gauge faster.',
    effectType: 'raid_gauge_charge_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.2, perLevel: 0.05, unit: 'percent'},
  }),
  skill({
    id: 'knight_battle_experience',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 4,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'knight_shield_charge',
    name: 'Battle Experience',
    shortDescription: 'Earn extra battle attack lines at max investment.',
    effectType: 'battle_attack_line_bonus',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {linesGrantedAtLevelFive: 1},
    notes: 'Grant one extra attack line when this node reaches level 5.',
  }),
  skill({
    id: 'knight_vanguard_banner',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 5,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'knight_battle_experience',
    name: 'Vanguard Banner',
    shortDescription: 'Gain attack while chaining stage clears.',
    effectType: 'level_mode_chain_clear_attack_rate',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'percent', cap: 0.2},
    extra: {maxConsecutiveClears: 20},
  }),
  skill({
    id: 'knight_fortress_armor',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 6,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'knight_vanguard_banner',
    name: 'Fortress Armor',
    shortDescription: 'Reduce endless obstacle spawn rate.',
    effectType: 'endless_obstacle_spawn_rate_reduction',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.25, perLevel: 0.05, unit: 'percent'},
  }),
  skill({
    id: 'knight_war_cry',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 7,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'knight_fortress_armor',
    name: 'War Cry',
    shortDescription: 'Gain a timed damage buff after combo 3.',
    effectType: 'timed_damage_buff_on_combo_3',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.5, perLevel: 0.1, unit: 'percent'},
    extra: {durationSec: 60},
  }),
  skill({
    id: 'knight_retaliation',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 8,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'knight_war_cry',
    name: 'Retaliation',
    shortDescription: 'Chance to counter attack after being hit.',
    effectType: 'counter_attack_chance',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.2, perLevel: 0.03, unit: 'chance'},
    extra: {damageMultiplier: 1},
  }),
  skill({
    id: 'knight_last_stand',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 9,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'knight_retaliation',
    name: 'Last Stand',
    shortDescription: 'Survive lethal damage once with a shield.',
    effectType: 'last_stand_with_shield',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {surviveHp: 1, shieldDurationSec: 10, freeContinue: true},
  }),
  skill({
    id: 'knight_royal_command',
    classId: 'knight',
    treeType: 'personal',
    legacyIndex: 10,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'knight_last_stand',
    name: 'Royal Command',
    shortDescription: 'Chance to auto clear an extra line on placement.',
    effectType: 'auto_clear_line_on_place',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
    extra: {countsAsCombo: true},
  }),
  skill({
    id: 'knight_guardian_wall',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 11,
    treeNodeIndex: 1,
    name: 'Guardian Wall',
    shortDescription: 'Reduce party incoming damage.',
    effectType: 'party_incoming_damage_reduction_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.15, perLevel: 0.03, unit: 'percent'},
  }),
  skill({
    id: 'knight_taunt_roar',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 12,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'knight_guardian_wall',
    name: 'Taunt Roar',
    shortDescription: 'Redirect boss pressure to the knight.',
    effectType: 'raid_taunt_window',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {durationSec: 20, cooldownSec: 60, selfDamageTakenRate: 0.2},
  }),
  skill({
    id: 'knight_charge_order',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 13,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'knight_taunt_roar',
    name: 'Charge Order',
    shortDescription: 'Increase party raid damage.',
    effectType: 'party_raid_damage_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'knight_battle_command',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 14,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'knight_charge_order',
    name: 'Battle Command',
    shortDescription: 'Increase party skill damage.',
    effectType: 'party_skill_damage_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'knight_fortress_formation',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 15,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'knight_battle_command',
    name: 'Fortress Formation',
    shortDescription: 'Chance to nullify boss special attacks.',
    effectType: 'boss_special_nullify_chance',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.2, perLevel: 0.04, unit: 'chance'},
  }),
  skill({
    id: 'knight_final_push',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 16,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'knight_fortress_formation',
    name: 'Final Push',
    shortDescription: 'Increase party damage against low HP bosses.',
    effectType: 'boss_execute_phase_party_damage_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.25, perLevel: 0.03, unit: 'percent'},
    extra: {bossHpThresholdRate: 0.2},
  }),
  skill({
    id: 'knight_morale_charge',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 17,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'knight_final_push',
    name: 'Morale Charge',
    shortDescription: 'Increase party skill gauge gain.',
    effectType: 'party_skill_gauge_charge_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'knight_protection_oath',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 18,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'knight_morale_charge',
    name: 'Protection Oath',
    shortDescription: 'Save a fallen ally once with a shield.',
    effectType: 'party_last_stand_support',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {surviveHp: 1, shieldDurationSec: 10, maxTriggersPerKnight: 1},
  }),
  skill({
    id: 'knight_victory_breakthrough',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 19,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'knight_protection_oath',
    name: 'Victory Breakthrough',
    shortDescription: 'Increase party raid rewards.',
    effectType: 'party_raid_reward_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'knight_united_force',
    classId: 'knight',
    treeType: 'party',
    legacyIndex: 20,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'knight_victory_breakthrough',
    name: 'United Force',
    shortDescription: 'Increase party attack per member.',
    effectType: 'party_attack_rate_per_member',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'percent'},
  }),
];

const mageSkills: SkillDefinition[] = [
  skill({
    id: 'mage_foresight',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 1,
    treeNodeIndex: 1,
    name: 'Foresight',
    shortDescription: 'Preview the next three pieces.',
    effectType: 'piece_preview_count',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {previewCount: 3},
  }),
  skill({
    id: 'mage_time_warp',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 2,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'mage_foresight',
    name: 'Time Warp',
    shortDescription: 'Slow endless difficulty gain.',
    effectType: 'endless_level_up_speed_reduction',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'mage_elemental_burst',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 3,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'mage_time_warp',
    name: 'Elemental Burst',
    shortDescription: 'Chance to clear an adjacent line after a line clear.',
    effectType: 'adjacent_line_clear_on_line_clear',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {countsAsCombo: true},
  }),
  skill({
    id: 'mage_mana_shield',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 4,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'mage_elemental_burst',
    name: 'Mana Shield',
    shortDescription: 'Chance to create a temporary shield after line clears.',
    effectType: 'temporary_shield_on_line_clear',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {durationSec: 10},
  }),
  skill({
    id: 'mage_block_summon',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 5,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'mage_mana_shield',
    name: 'Block Summon',
    shortDescription: 'Chance to drop 1-2 filler cells into the board.',
    effectType: 'filler_cells_on_place',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.02, perLevel: 0.01, unit: 'chance'},
    extra: {minCells: 1, maxCells: 2},
  }),
  skill({
    id: 'mage_alchemy',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 6,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'mage_block_summon',
    name: 'Alchemy',
    shortDescription: 'Chance to spawn a diamond cell on placement.',
    effectType: 'diamond_cell_spawn_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.01, perLevel: 0.005, unit: 'chance'},
  }),
  skill({
    id: 'mage_arcane_choice',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 7,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'mage_alchemy',
    name: 'Arcane Choice',
    shortDescription: 'Chance to pick a desired block from a spellbook.',
    effectType: 'piece_pick_spellbook_chance',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.02, perLevel: 0.005, unit: 'chance'},
  }),
  skill({
    id: 'mage_arcane_amplify',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 8,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'mage_arcane_choice',
    name: 'Arcane Amplify',
    shortDescription: 'Increase fever gauge charge speed.',
    effectType: 'fever_gauge_charge_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.15, perLevel: 0.03, unit: 'percent'},
  }),
  skill({
    id: 'mage_dimensional_rift',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 9,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'mage_arcane_amplify',
    name: 'Dimensional Rift',
    shortDescription: 'Clear a random line after combo 3.',
    effectType: 'random_line_clear_on_combo_3',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {countsAsCombo: true},
  }),
  skill({
    id: 'mage_mana_conversion',
    classId: 'mage',
    treeType: 'personal',
    legacyIndex: 10,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'mage_dimensional_rift',
    name: 'Mana Conversion',
    shortDescription: 'Chance to drop five mana cells onto the board.',
    effectType: 'multi_cell_drop_on_place',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.02, perLevel: 0.005, unit: 'chance'},
    extra: {cellCount: 5},
  }),
  skill({
    id: 'mage_mana_share',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 11,
    treeNodeIndex: 1,
    name: 'Mana Share',
    shortDescription: 'Increase party base attack.',
    effectType: 'party_base_attack_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'percent'},
  }),
  skill({
    id: 'mage_light_of_wisdom',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 12,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'mage_mana_share',
    name: 'Light of Wisdom',
    shortDescription: 'Grant one-piece preview to the party.',
    effectType: 'party_piece_preview_count',
    stackingRule: 'highest_same_skill',
    complexity: 'advanced',
    extra: {previewCount: 1},
  }),
  skill({
    id: 'mage_spacetime_warp',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 13,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'mage_light_of_wisdom',
    name: 'Spacetime Warp',
    shortDescription: 'Add raid time for the party.',
    effectType: 'party_raid_time_bonus_sec',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 15, perLevel: 3, unit: 'seconds'},
  }),
  skill({
    id: 'mage_elemental_harmony',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 14,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'mage_spacetime_warp',
    name: 'Elemental Harmony',
    shortDescription: 'Boost line clear damage for the party.',
    effectType: 'party_line_clear_damage_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.12, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'mage_arcane_overdrive',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 15,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'mage_elemental_harmony',
    name: 'Arcane Overdrive',
    shortDescription: 'Extend party fever duration.',
    effectType: 'party_fever_duration_bonus_sec',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 3, perLevel: 1, unit: 'seconds'},
  }),
  skill({
    id: 'mage_mystic_supply',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 16,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'mage_arcane_overdrive',
    name: 'Mystic Supply',
    shortDescription: 'Grant a free raid item to the party.',
    effectType: 'party_free_raid_item_grant',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {itemCount: 1},
  }),
  skill({
    id: 'mage_focus_link',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 17,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'mage_mystic_supply',
    name: 'Focus Link',
    shortDescription: 'Extend combo duration for the party.',
    effectType: 'party_combo_window_bonus_sec',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 5, perLevel: 1, unit: 'seconds'},
  }),
  skill({
    id: 'mage_party_mana_shield',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 18,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'mage_focus_link',
    name: 'Party Mana Shield',
    shortDescription: 'Shield low HP party members once.',
    effectType: 'party_low_hp_shield_once',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {hpThresholdRate: 0.1, durationSec: 5},
  }),
  skill({
    id: 'mage_arcane_release',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 19,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'mage_party_mana_shield',
    name: 'Arcane Release',
    shortDescription: 'Lower party fever requirement in boss execute phase.',
    effectType: 'party_fever_requirement_reduction_execute_phase',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.2, perLevel: 0.02, unit: 'percent'},
    extra: {bossHpThresholdRate: 0.5},
  }),
  skill({
    id: 'mage_magic_circle',
    classId: 'mage',
    treeType: 'party',
    legacyIndex: 20,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'mage_arcane_release',
    name: 'Magic Circle',
    shortDescription: 'Chance to trigger party fever on line clears.',
    effectType: 'party_fever_proc_on_line_clear',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
  }),
];

const archerSkills: SkillDefinition[] = [
  skill({
    id: 'archer_rapid_fire',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 1,
    treeNodeIndex: 1,
    name: 'Rapid Fire',
    shortDescription: 'Increase small piece rate and two-piece streak damage.',
    effectType: 'small_piece_rate_and_two_streak_damage',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {smallPieceRate: 0.25, twoStreakDamageRate: 0.2},
  }),
  skill({
    id: 'archer_quick_place',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 2,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'archer_rapid_fire',
    name: 'Quick Place',
    shortDescription: 'Gain stacking flat damage on fast placements.',
    effectType: 'fast_place_flat_damage_stacks',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 5, perLevel: 2, unit: 'flat'},
    extra: {windowSec: 2},
  }),
  skill({
    id: 'archer_precision_shot',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 3,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'archer_quick_place',
    name: 'Precision Shot',
    shortDescription: 'Reward sequential larger line clears.',
    effectType: 'sequential_line_clear_precision_bonus',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {bonusTwoLines: 0.2, bonusThreeLines: 0.3, bonusFourLines: 0.5},
  }),
  skill({
    id: 'archer_barrage',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 4,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'archer_precision_shot',
    name: 'Barrage',
    shortDescription: 'Gain extra damage during fever.',
    effectType: 'fever_damage_bonus_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.2, perLevel: 0.05, unit: 'percent'},
  }),
  skill({
    id: 'archer_arrow_rain',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 5,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'archer_barrage',
    name: 'Arrow Rain',
    shortDescription: 'Trigger vertical destruction after combo 3.',
    effectType: 'random_column_clear_on_combo_3',
    stackingRule: 'self_only',
    complexity: 'vfx',
    extra: {destroyedLineMin: 1, destroyedLineMax: 2, countsAsCombo: true},
  }),
  skill({
    id: 'archer_hawk_eye',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 6,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'archer_arrow_rain',
    name: 'Hawk Eye',
    shortDescription: 'Highlight valid and high-value placements.',
    effectType: 'placement_hint_overlay',
    stackingRule: 'self_only',
    complexity: 'vfx',
    extra: {showGoldenFinisherHints: true},
  }),
  skill({
    id: 'archer_piercing_shot',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 7,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'archer_hawk_eye',
    name: 'Piercing Shot',
    shortDescription: 'Chance to manually clear a dragged line.',
    effectType: 'manual_line_clear_on_proc',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {countsAsCombo: true},
  }),
  skill({
    id: 'archer_blessing_of_wind',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 8,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'archer_piercing_shot',
    name: 'Blessing of Wind',
    shortDescription: 'Chance to double the fever multiplier.',
    effectType: 'double_fever_multiplier_proc',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.2, perLevel: 0.03, unit: 'chance'},
    extra: {bonusFeverMultiplier: 2},
  }),
  skill({
    id: 'archer_focused_aim',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 9,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'archer_blessing_of_wind',
    name: 'Focused Aim',
    shortDescription: 'Reduce fever line requirement.',
    effectType: 'fever_requirement_reduction_rate',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.3, perLevel: 0.03, unit: 'percent'},
  }),
  skill({
    id: 'archer_instinctive_evade',
    classId: 'archer',
    treeType: 'personal',
    legacyIndex: 10,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'archer_focused_aim',
    name: 'Instinctive Evade',
    shortDescription: 'Chance to negate incoming attacks with cooldown.',
    effectType: 'incoming_attack_negate_chance',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.3, perLevel: 0.04, unit: 'chance'},
    extra: {cooldownSec: 10},
  }),
  skill({
    id: 'archer_support_fire',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 11,
    treeNodeIndex: 1,
    name: 'Support Fire',
    shortDescription: 'Increase party line clear damage.',
    effectType: 'party_line_clear_damage_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.08, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'archer_recon',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 12,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'archer_support_fire',
    name: 'Recon',
    shortDescription: 'Reveal boss pattern countdowns early.',
    effectType: 'boss_pattern_warning_sec',
    stackingRule: 'highest_same_skill',
    complexity: 'vfx',
    scaling: {baseValue: 5, perLevel: 1, unit: 'seconds'},
  }),
  skill({
    id: 'archer_arrow_salvo',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 13,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'archer_recon',
    name: 'Arrow Salvo',
    shortDescription: 'Trigger extra boss damage when allies hit combo 3.',
    effectType: 'party_extra_damage_on_combo_3',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {damageMultiplier: 2},
  }),
  skill({
    id: 'archer_weak_point',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 14,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'archer_arrow_salvo',
    name: 'Weak Point',
    shortDescription: 'Chance to expose a boss weak point for party damage.',
    effectType: 'boss_weak_point_window',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.03, perLevel: 0.01, unit: 'chance'},
    extra: {durationSec: 10, partyDamageRate: 0.3},
  }),
  skill({
    id: 'archer_smoke_arrow',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 15,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'archer_weak_point',
    name: 'Smoke Arrow',
    shortDescription: 'Delay boss special preparation and cadence.',
    effectType: 'boss_pattern_delay',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {patternDelaySec: 1, cadenceDelayRate: 0.1},
  }),
  skill({
    id: 'archer_position_support',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 16,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'archer_smoke_arrow',
    name: 'Position Support',
    shortDescription: 'Increase party small-piece rate.',
    effectType: 'party_small_piece_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'archer_wind_stride',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 17,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'archer_position_support',
    name: 'Wind Stride',
    shortDescription: 'Boost fast-placement bonus using base attack.',
    effectType: 'party_fast_place_attack_bonus',
    stackingRule: 'highest_same_skill',
    complexity: 'advanced',
    extra: {windowSec: 2, maxStacks: 10},
  }),
  skill({
    id: 'archer_poison_arrow',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 18,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'archer_wind_stride',
    name: 'Poison Arrow',
    shortDescription: 'Apply a stacking damage-over-time effect to bosses.',
    effectType: 'boss_dot_on_party_line_clear',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {durationSec: 5, maxStacks: 5},
  }),
  skill({
    id: 'archer_gale_support',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 19,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'archer_poison_arrow',
    name: 'Gale Support',
    shortDescription: 'Chance to trigger a second attack for the party.',
    effectType: 'party_double_attack_proc',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.05, perLevel: 0.02, unit: 'chance'},
  }),
  skill({
    id: 'archer_master_focus',
    classId: 'archer',
    treeType: 'party',
    legacyIndex: 20,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'archer_gale_support',
    name: 'Master Focus',
    shortDescription: 'Increase gale support proc chance per party member.',
    effectType: 'party_double_attack_proc_per_member',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.04, perLevel: 0.01, unit: 'chance'},
    extra: {capRate: 0.2},
  }),
];

const rogueSkills: SkillDefinition[] = [
  skill({
    id: 'rogue_treasure_hunter',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 1,
    treeNodeIndex: 1,
    name: 'Treasure Hunter',
    shortDescription: 'Increase diamond cell rate and bonus diamonds.',
    effectType: 'diamond_drop_rate_and_bonus',
    stackingRule: 'self_only',
    complexity: 'core',
    extra: {diamondCellRateBonus: 0.05, bonusDiamondChance: 0.1},
  }),
  skill({
    id: 'rogue_rare_sense',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 2,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'rogue_treasure_hunter',
    name: 'Rare Sense',
    shortDescription: 'Increase rare item block rates.',
    effectType: 'rare_item_block_rate_bonus',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'rogue_lucky_dice',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 3,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'rogue_rare_sense',
    name: 'Lucky Dice',
    shortDescription: 'Chance to double line clear damage or score.',
    effectType: 'double_line_clear_result_chance',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
  }),
  skill({
    id: 'rogue_shadow_hands',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 4,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'rogue_lucky_dice',
    name: 'Shadow Hands',
    shortDescription: 'Chance to enable piece rotation on generated pieces.',
    effectType: 'piece_rotation_unlock_chance',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
  }),
  skill({
    id: 'rogue_stealth',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 5,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'rogue_shadow_hands',
    name: 'Stealth',
    shortDescription: 'Chance to gain temporary damage reduction on placement.',
    effectType: 'temporary_damage_reduction_on_place',
    stackingRule: 'self_only',
    complexity: 'advanced',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {durationSec: 3, damageReductionRate: 0.5, cooldownSec: 10},
  }),
  skill({
    id: 'rogue_plunder',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 6,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'rogue_stealth',
    name: 'Plunder',
    shortDescription: 'Chance to increase clear rewards and bonus diamonds.',
    effectType: 'reward_bonus_on_victory',
    stackingRule: 'self_only',
    complexity: 'server',
    extra: {rewardBonusChance: 0.3, rewardBonusRate: 0.2, extraDiamondChance: 0.05},
  }),
  skill({
    id: 'rogue_silent_strike',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 7,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'rogue_plunder',
    name: 'Silent Strike',
    shortDescription: 'Store a skill-break attack after combo 3.',
    effectType: 'skill_break_charge_on_combo_3',
    stackingRule: 'self_only',
    complexity: 'server',
    extra: {procChance: 0.2, normalDamageRate: 0.2, interruptDamageMultiplier: 2},
  }),
  skill({
    id: 'rogue_jackpot',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 8,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'rogue_silent_strike',
    name: 'Jackpot',
    shortDescription: 'Chance to triple clear rewards.',
    effectType: 'reward_tripler_chance',
    stackingRule: 'self_only',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {rewardMultiplier: 3},
  }),
  skill({
    id: 'rogue_hidden_pocket',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 9,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'rogue_jackpot',
    name: 'Hidden Pocket',
    shortDescription: 'Increase item cap and start with a bonus item.',
    effectType: 'inventory_cap_bonus_and_start_item',
    stackingRule: 'self_only',
    complexity: 'server',
    extra: {extraItemTypes: 2, extraItemCapPerType: 1, startBonusItemCount: 1},
  }),
  skill({
    id: 'rogue_cunning_eye',
    classId: 'rogue',
    treeType: 'personal',
    legacyIndex: 10,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'rogue_hidden_pocket',
    name: 'Cunning Eye',
    shortDescription: 'Reduce shop and refresh costs.',
    effectType: 'shop_discount_rate',
    stackingRule: 'self_only',
    complexity: 'server',
    extra: {shopDiscountRate: 0.15, refreshDiscountRate: 0.3},
  }),
  skill({
    id: 'rogue_loot_share',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 11,
    treeNodeIndex: 1,
    name: 'Loot Share',
    shortDescription: 'Increase party currency rewards.',
    effectType: 'party_currency_reward_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'rogue_fortune_of_thieves',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 12,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'rogue_loot_share',
    name: 'Fortune of Thieves',
    shortDescription: 'Increase high-grade raid reward rates.',
    effectType: 'party_high_grade_reward_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'rogue_hidden_support',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 13,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'rogue_fortune_of_thieves',
    name: 'Hidden Support',
    shortDescription: 'Chance to negate party debuffs.',
    effectType: 'party_debuff_negate_chance',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.15, perLevel: 0.03, unit: 'chance'},
  }),
  skill({
    id: 'rogue_trap_setup',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 14,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'rogue_hidden_support',
    name: 'Trap Setup',
    shortDescription: 'Delay boss special cooldowns.',
    effectType: 'boss_special_cooldown_delay_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.15, perLevel: 0.03, unit: 'percent'},
  }),
  skill({
    id: 'rogue_marked_target',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 15,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'rogue_trap_setup',
    name: 'Marked Target',
    shortDescription: 'Apply stacking party damage mark on combo 4.',
    effectType: 'boss_mark_stack_on_party_combo_4',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {damageRatePerStack: 0.08, maxStacks: 5, durationSec: 5},
  }),
  skill({
    id: 'rogue_shadow_clone',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 16,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'rogue_marked_target',
    name: 'Shadow Clone',
    shortDescription: 'Chance to deal bonus shadow damage after line clears.',
    effectType: 'shadow_hit_on_party_line_clear',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'chance'},
    extra: {damageRate: 0.5},
  }),
  skill({
    id: 'rogue_treasure_map',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 17,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'rogue_shadow_clone',
    name: 'Treasure Map',
    shortDescription: 'Increase hidden chest rates in raids.',
    effectType: 'hidden_chest_rate_bonus',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.2, perLevel: 0.03, unit: 'percent'},
  }),
  skill({
    id: 'rogue_poison_coating',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 18,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'rogue_treasure_map',
    name: 'Poison Coating',
    shortDescription: 'Apply stacking incoming-damage debuff to bosses.',
    effectType: 'boss_incoming_damage_taken_debuff',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {ratePerStack: 0.03, maxStacks: 5, durationSec: 5},
  }),
  skill({
    id: 'rogue_escape_smoke',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 19,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'rogue_poison_coating',
    name: 'Escape Smoke',
    shortDescription: 'Save the party once from wipe or timeout.',
    effectType: 'party_fail_save_window',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {extraTimeSec: 60, bossStopSec: 5, cooldownSec: 1200},
  }),
  skill({
    id: 'rogue_black_market',
    classId: 'rogue',
    treeType: 'party',
    legacyIndex: 20,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'rogue_escape_smoke',
    name: 'Black Market',
    shortDescription: 'Grant temporary support items on combo 3.',
    effectType: 'temporary_support_item_grant_on_combo_3',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {itemCountPerPartyMember: 1},
  }),
];

const healerSkills: SkillDefinition[] = [
  skill({
    id: 'healer_recovery',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 1,
    treeNodeIndex: 1,
    name: 'Recovery',
    shortDescription: 'Automatically heal on cooldown when HP is low.',
    effectType: 'auto_heal_on_cooldown',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {cooldownSec: 60, hpThresholdRate: 0.5, healRate: 0.1},
  }),
  skill({
    id: 'healer_blessed_setup',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 2,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'healer_recovery',
    name: 'Blessed Setup',
    shortDescription: 'Pre-place the first three pieces in level mode.',
    effectType: 'level_mode_preparation_turns',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {preparedPieceCount: 3},
  }),
  skill({
    id: 'healer_healing_touch',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 3,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'healer_blessed_setup',
    name: 'Healing Touch',
    shortDescription: 'Heal after accumulating line clears.',
    effectType: 'heal_on_clears_accumulated',
    stackingRule: 'self_only',
    complexity: 'core',
    extra: {requiredClears: 5, healRate: 0.15},
  }),
  skill({
    id: 'healer_vitality',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 4,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'healer_healing_touch',
    name: 'Vitality',
    shortDescription: 'Increase heart capacity and improve heart regeneration.',
    effectType: 'heart_capacity_and_regen_bonus',
    stackingRule: 'self_only',
    complexity: 'server',
    extra: {extraHearts: 1, regenReductionRate: 0.2},
  }),
  skill({
    id: 'healer_regeneration_light',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 5,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'healer_vitality',
    name: 'Regeneration Light',
    shortDescription: 'Heal every two line clears.',
    effectType: 'heal_every_two_clears',
    stackingRule: 'self_only',
    complexity: 'core',
    extra: {requiredClears: 2, healRate: 0.05},
  }),
  skill({
    id: 'healer_serenity',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 6,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'healer_regeneration_light',
    name: 'Serenity',
    shortDescription: 'Extend combo timer once before it breaks.',
    effectType: 'combo_save_extension',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {extensionSec: 3, cooldownSec: 20},
  }),
  skill({
    id: 'healer_miracle',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 7,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'healer_serenity',
    name: 'Miracle',
    shortDescription: 'Chance to draw a custom temporary piece.',
    effectType: 'custom_piece_draw_proc',
    stackingRule: 'self_only',
    complexity: 'vfx',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
    extra: {gridWidth: 5, gridHeight: 4, minCells: 3, maxCells: 7},
  }),
  skill({
    id: 'healer_care',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 8,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'healer_miracle',
    name: 'Care',
    shortDescription: 'Chance to preserve used items.',
    effectType: 'item_preserve_chance',
    stackingRule: 'self_only',
    complexity: 'server',
    scaling: {baseValue: 0.2, perLevel: 0.03, unit: 'chance'},
  }),
  skill({
    id: 'healer_divine_strike',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 9,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'healer_care',
    name: 'Divine Strike',
    shortDescription: 'Build exponential strike power after double clears.',
    effectType: 'stacking_divine_strike_charge',
    stackingRule: 'self_only',
    complexity: 'advanced',
    extra: {requiredLinesPerCharge: 2, chargeMultiplier: 1.3, maxCharges: 20},
  }),
  skill({
    id: 'healer_soul_harvest',
    classId: 'healer',
    treeType: 'personal',
    legacyIndex: 10,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'healer_divine_strike',
    name: 'Soul Harvest',
    shortDescription: 'Heal based on the number of lines cleared at once.',
    effectType: 'heal_per_line_cleared',
    stackingRule: 'self_only',
    complexity: 'core',
    scaling: {baseValue: 0.01, perLevel: 0.002, unit: 'percent'},
  }),
  skill({
    id: 'healer_party_healing_touch',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 11,
    treeNodeIndex: 1,
    name: 'Party Healing Touch',
    shortDescription: 'Chance to heal the party when the healer places pieces.',
    effectType: 'party_heal_on_place',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
    extra: {healRate: 0.05},
  }),
  skill({
    id: 'healer_regeneration_aura',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 12,
    treeNodeIndex: 2,
    prerequisiteSkillId: 'healer_party_healing_touch',
    name: 'Regeneration Aura',
    shortDescription: 'Heal the party over time.',
    effectType: 'party_regeneration_aura',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {durationSec: 10, healPerSecondRate: 0.02, cooldownSec: 30},
  }),
  skill({
    id: 'healer_blessing_of_light',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 13,
    treeNodeIndex: 3,
    prerequisiteSkillId: 'healer_regeneration_aura',
    name: 'Blessing of Light',
    shortDescription: 'Grant random support items at run start.',
    effectType: 'party_starting_support_items',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {itemCount: 2, temporary: true},
  }),
  skill({
    id: 'healer_purifying_wind',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 14,
    treeNodeIndex: 4,
    prerequisiteSkillId: 'healer_blessing_of_light',
    name: 'Purifying Wind',
    shortDescription: 'Chance to remove party debuffs on line clear.',
    effectType: 'party_cleanse_on_line_clear',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
  }),
  skill({
    id: 'healer_fountain_of_life',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 15,
    treeNodeIndex: 5,
    prerequisiteSkillId: 'healer_purifying_wind',
    name: 'Fountain of Life',
    shortDescription: 'Add raid time for the party.',
    effectType: 'party_raid_time_bonus_sec',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 60, perLevel: 10, unit: 'seconds'},
  }),
  skill({
    id: 'healer_healing_wave',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 16,
    treeNodeIndex: 6,
    prerequisiteSkillId: 'healer_fountain_of_life',
    name: 'Healing Wave',
    shortDescription: 'Chance to grant the party a shield on placement.',
    effectType: 'party_shield_on_place',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.05, perLevel: 0.01, unit: 'chance'},
    extra: {shieldDurationSec: 5, internalCooldownSec: 10},
  }),
  skill({
    id: 'healer_holy_ground',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 17,
    treeNodeIndex: 7,
    prerequisiteSkillId: 'healer_healing_wave',
    name: 'Holy Ground',
    shortDescription: 'Increase party gold and gem income.',
    effectType: 'party_currency_reward_rate',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.1, perLevel: 0.02, unit: 'percent'},
  }),
  skill({
    id: 'healer_resurrection_miracle',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 18,
    treeNodeIndex: 8,
    prerequisiteSkillId: 'healer_holy_ground',
    name: 'Resurrection Miracle',
    shortDescription: 'Allow one party retry on raid failure.',
    effectType: 'party_raid_retry_once',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {reviveHpRate: 0.5, cooldownSec: 1200},
  }),
  skill({
    id: 'healer_soul_link',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 19,
    treeNodeIndex: 9,
    prerequisiteSkillId: 'healer_resurrection_miracle',
    name: 'Soul Link',
    shortDescription: 'Grant combo bonus when an ally hits combo 5.',
    effectType: 'party_combo_bonus_on_combo_5',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    extra: {comboBonus: 2, durationSec: 5},
  }),
  skill({
    id: 'healer_natures_blessing',
    classId: 'healer',
    treeType: 'party',
    legacyIndex: 20,
    treeNodeIndex: 10,
    prerequisiteSkillId: 'healer_soul_link',
    name: 'Natures Blessing',
    shortDescription: 'Increase party max HP per member.',
    effectType: 'party_max_hp_rate_per_member',
    stackingRule: 'highest_same_skill',
    complexity: 'server',
    scaling: {baseValue: 0.03, perLevel: 0.005, unit: 'percent'},
    extra: {capRate: 0.3},
  }),
];

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  ...knightSkills,
  ...mageSkills,
  ...archerSkills,
  ...rogueSkills,
  ...healerSkills,
];

export function getStagesForWorld(worldId: number): StageDefinition[] {
  return STAGE_DEFINITIONS.filter(stage => stage.worldId === worldId);
}

export function getRaidBossByStage(stage: number): BossRaidDefinition | undefined {
  return BOSS_RAID_DEFINITIONS.find(boss => boss.stage === stage);
}

export function getSkillsForClass(classId: CharacterDefinition['id']): SkillDefinition[] {
  return SKILL_DEFINITIONS.filter(skillDef => skillDef.classId === classId);
}

export {skill};
